# -*- coding: utf-8 -*-
"""Movie_recommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Abdul-pitodia/Movie_recommender_python/blob/main/Movie_recommendation.ipynb
"""

import pandas as pd

movie = pd.read_csv('main_data.csv')

movie.head()

movie.info()

movie['index'] = movie.reset_index().index

movie.head()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# creating a count matrix
cv = CountVectorizer()
count_matrix = cv.fit_transform(movie['comb'])
# creating a similarity score matrix
similarity = cosine_similarity(count_matrix)
print(count_matrix.toarray())

def get_index_from_title(title):
    return movie[movie['movie_title'] == title]["index"].values[0]

get_movie = input().lower()
try:
  movie_index = get_index_from_title(get_movie)
except:
  print('Movie not found.')

similar_movies = list(enumerate(similarity[movie_index]))
similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[:15]
print(similar_movies)

def get_title_from_index(index):
  return movie[movie['index'] == index]['movie_title'].values[0]

movies_lst = []
for idx,cos in similar_movies:
  movies_lst.append(get_title_from_index(idx))

for i in range(1,len(movies_lst)):
  print(movies_lst[i].title())

